[package]
name = "isle_fuzzing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cranelift-isle = { path = "../../isle" } 

[[bin]]
name = "expr"
path = "src/expr.rs"
