name: aslp

on:
  push:
    branches:
      - veriisle
    paths:
      - '.github/workflows/aslp.yml'
      - '**/aslp/**'
  pull_request:
    branches:
      - veriisle
    paths:
      - '.github/workflows/aslp.yml'
      - '**/aslp/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ASLP_PATH: ${{ github.workspace }}/tools/aslp
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: Install LLVM
        env:
          LLVM_VERSION: 18
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh "${LLVM_VERSION}"
          echo "/usr/lib/llvm-${LLVM_VERSION}/bin" >> "${GITHUB_PATH}"
      - name: Install OPAM
        run: sudo apt-get install -y opam
      - name: Cache ASLp
        id: cache-aslp
        uses: actions/cache@v4
        with:
          path: ${{ env.ASLP_PATH }}
          key: aslp-${{ runner.os }}-${{ hashFiles('main/cranelift/isle/veri/veri/script/install/aslp.sh') }}
      - name: Install ASLp
        if: steps.cache-aslp.outputs.cache-hit != 'true'
        working-directory: main/cranelift/isle/veri/veri
        run: |
          mkdir -p "${ASLP_PATH}"
          ./script/install/aslp.sh -i "${ASLP_PATH}" -t "${RUNNER_TEMP}"
      - name: Configure ASLp
        run: echo "${ASLP_PATH}/bin" >> $GITHUB_PATH
      - name: Generate ASLp Test Data
        working-directory: main/cranelift/isle/veri/aslp/tests/data
        run: ./generate.sh
      - name: Git Status
        working-directory: main
        run: |
          git diff
          test -z "$(git status --porcelain)"
